---
title: "Library"
# output:
#   html_document:
#     theme: flatly
---

### Resources

-   [Data Portal User Guide](http://docs.nsercresnet.ca/data-portal-guide/){target="_blank"}
-   ResNet Metadata Questionnaire Form v1.0 ([Google Document](https://docs.google.com/document/d/17_JSYg62wC2alPnd7VsxYzYmadRJkHyNO-QOon0-xB4/edit?usp=sharing){target="_blank"})

### Presentations

-   2021-10-29: Metadata Training ([Google Slides](https://docs.google.com/presentation/d/17MwEvf0QfGcrHkv3EZAbYMBLauSgJya8xeBm8oNkuiU/edit?usp=sharing){target="_blank"}, [PDF](pdfs/ResNet%20Metadata%20Training%2020211029%20archive.pdf){target="_blank"})
-   2021-10-15: Data Policy ([Google Slides](https://docs.google.com/presentation/d/1tYxQas8iBCHmPuORAEaGmBYcr3HhwOxi84IKWlzKhQs/edit?usp=sharing){target="_blank"}, [PDF](pdfs/ResNet%20Data%20Policy%20-%20Monthly%20Meeting%2020211015%20archive.pdf){target="_blank"})
-   2021-05-07: AGM 2021 Dashboards & Data Management ([Google Slides](https://docs.google.com/presentation/d/1Fr8cN4jJoV6gFNnB-6O3eJiBMRA0XiHGvDHOz4pkpio/edit?usp=sharing){target="_blank"}, [PDF](pdfs/ResNet%20AGM2021%20Dashboard%20Data%20Mgmt%2020210507%20archive.pdf){target="_blank"})

### Network Policy

- ResNet Data Policy ([PDF](pdfs/ResNet%20Data%20Policy.pdf){target="_blank"})

### External

-   Good enough practices in scientific computing. Wilson et al., 2017 ([DOI](https://doi.org/10.1371/journal.pcbi.1005510){target="_blank"}, [PDF](pdfs/Good-Enough-Computing_Wilson_2017.pdf){target="_blank"})
-   Operationalizing the CARE and FAIR Principles for Indigenous data futures. Carroll et al., 2021 ([DOI](https://doi.org/10.1038/s41597-021-00892-0){target="_blank"}, [PDF](pdfs/Operationalize-CARE-FAIR_Carroll_2021.pdf){target="_blank"})

### Links

-   [ResNet Home](https://www.nsercresnet.ca){target="_blank"}
-   [ResNet Data Portal](https://data.nsercresnet.ca){target="_blank"}
-   [ResNet Metadata Questionnaire](https://apps.nsercresnet.ca/){target="_blank"}
